### ISSUE TITLE
zz_interpol recipe failing

### ISSUE THREAD

**Issue by vabiro** [pudo/opennames#7]
Hi,

Thank you for all the fantastic work that you've done. It is a really great tool, and I look forward to working with it.

I have managed to get it to do most sources that are available, but it keeps failing on a "Identity unknown" subject on the scrape of the zz_interpol redlist.

Here is the response:

make -C zz_interpol scrape
make[2]: Entering directory '/var/www/wiirkspace/beta/opennames-master/sources/zz_interpol'
mkdir -p /20170304
python scrape.py /20170304/zz_interpol.json
Storing to JSON: /20170304/zz_interpol.json
Wanted: RICHARD, NICHOLAS T.
Wanted: FERNANDEZ TORRES, PEDRO RAMON
Wanted: ANTUNEZ, JUAN ALBERTO
Wanted: BENITEZ, CARMELO JUAN
Wanted: BENITEZ, FABIAN CARMELO
Traceback (most recent call last):
  File "scrape.py", line 55, in <module>
    scrape(sys.argv[1])
  File "scrape.py", line 48, in scrape
    cases.append(scrape_case(case_url))
  File "scrape.py", line 28, in scrape_case
    if len(name):
TypeError: object of type 'NoneType' has no len()
Makefile:7: recipe for target '/20170304/zz_interpol.json' failed
make[2]: *** [/20170304/zz_interpol.json] Error 1
make[2]: Leaving directory '/var/www/wiirkspace/beta/opennames-master/sources/zz_interpol'
Makefile:15: recipe for target 'zz_interpol.scrape' failed
make[1]: *** [zz_interpol.scrape] Error 2
make[1]: Leaving directory '/var/www/wiirkspace/beta/opennames-master/sources'
Makefile:5: recipe for target 'scrape' failed
make: *** [scrape] Error 2

It seems to work fine on the full record, but fails with type 'NoneType' error when the name isn't a normal name.

I have tried changing line 28 from "if len(name):" to "if not len(name):" which sometimes fixes when the len() hangs on type 'NoneType', but that didn't work.

Anyone have some thoughts on how we could get the scraper to tolerate this?

Thanks.

**Comment by pudo** [comment]
please let me know if this fix works for you :)

**Comment by vabiro** [comment]
I feel like such a jerk. I should have gotten back to you much quicker, especially given how quickly you did a fix.

It is working like a champ. Thank you again for all your work.
